version: '3'

services:
  bot:
    image: meeting-bot:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/meeting-bot/logs
    command: python3 app.py
    network_mode: host

  auth-bot:
    image: meeting-bot:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/meeting-bot/logs
    command: python3 auth.py
    network_mode: host
    ports:
      - "3000:3000"

  oauth-server:
    image: meeting-bot:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/meeting-bot/logs
    command: python3 oauth_server.py
    network_mode: host
    ports:
      - "5000:5000"