version: '3'

services:
  bot:
    image: meeting-bot:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/meeting-bot
    command: python3 app.py
    network_mode: host

  auth-bot:
    image: meeting-bot:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/meeting-bot
    command: python3 auth.py
    environment:
      - NGROK_AUTH_TOKEN=${NGROK_AUTH_TOKEN}

  oauth-server:
    image: meeting-bot:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/meeting-bot
    command: python3 oauth_server.py
    network_mode: "host"
    environment:
      - NGROK_AUTH_TOKEN=${NGROK_AUTH_TOKEN}
